### ISSUE TITLE
Tile Refresh Issue

### ISSUE THREAD

**Issue by fennean1** [fennean1/JellyJammerGame#1]
Refreshing the grid after swapping will cause the swapped tiles to "blink" when they're refreshed. 

However, the tiles will only "blink" if the were swapped either left or right.

 Swapping up and down before refreshing will not cause this issue.

**Comment by fennean1** [comment]
This was a key issue caused by the fact that the tile components were being stored in a 2D array.

Rendering with a 1D array works fine and fixes the issue.

**Comment by ninkambazi** [comment]
it doesnt swipe
